apiVersion: v1
kind: PeristentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      label:
        app: mysql
    spec:
      containers:
      - image: danilo/projeto-database:1.0
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
        
        volumeMounts:
        - name: mysql-dados
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-dados
        peristentVolumeClaim:
          claimName: mysql-dados

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: php       
        image: danilo/projeto-backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
